const categoriesData = [
  { _id: 'cat_1', name: 'T-Shirts', slug: 't-shirts', description: 'Heavyweight organic cotton tees.', image: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=800&q=80', isActive: true },
  { _id: 'cat_2', name: 'Shirts', slug: 'shirts', description: 'Tailored button-downs.', image: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&q=80', isActive: true },
  { _id: 'cat_3', name: 'Hoodies', slug: 'hoodies', description: 'French terry fleeces.', image: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=800&q=80', isActive: true },
  { _id: 'cat_4', name: 'Jackets', slug: 'jackets', description: 'Minimal outerwear.', image: 'https://images.unsplash.com/photo-1548883354-7622d03aca27?w=800&q=80', isActive: true },
  { _id: 'cat_5', name: 'Jeans', slug: 'jeans', description: 'Raw & selvedge denim.', image: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=800&q=80', isActive: true },
  { _id: 'cat_6', name: 'Trousers', slug: 'trousers', description: 'Pleated wide-leg trousers.', image: 'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=800&q=80', isActive: true },
  { _id: 'cat_7', name: 'Dresses', slug: 'dresses', description: 'Silk slip & ribbed midi dresses.', image: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800&q=80', isActive: true },
  { _id: 'cat_8', name: 'Accessories', slug: 'accessories', description: 'Leather totes & beanies.', image: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=800&q=80', isActive: true }
];

const productsData = [
  {
    _id: 'prod_1',
    name: 'Heavyweight Boxy Tee',
    slug: 'heavyweight-boxy-tee',
    description: 'Constructed from 280 GSM 100% organic combed cotton, this heavyweight boxy tee features a rib collar, dropped shoulders, and a clean minimalist aesthetic.',
    shortDescription: '280 GSM heavyweight organic cotton tee with dropped shoulders.',
    brand: 'AURA Studio',
    category: 'T-Shirts',
    gender: 'unisex',
    collectionName: 'Minimal Essentials',
    price: 1899,
    compareAtPrice: 2499,
    discountPercentage: 24,
    images: [
      'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=1000&q=80',
      'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=1000&q=80'
    ],
    colors: ['Off-White', 'Black', 'Sand'],
    sizes: ['S', 'M', 'L', 'XL'],
    stock: 45,
    sku: 'TEE-BOX-001',
    material: '100% Organic Combed Cotton',
    careInstructions: 'Machine wash cold inside out. Line dry in shade.',
    tags: ['tshirt', 'cotton', 'boxy', 'minimal'],
    rating: 4.8,
    reviewCount: 34,
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: true,
    isActive: true,
    createdAt: new Date()
  },
  {
    _id: 'prod_2',
    name: 'Oversized Washed Graphic Tee',
    slug: 'oversized-washed-graphic-tee',
    description: 'Vintage vintage-wash tee featuring custom minimalist typography artwork on the chest and back. Enzyme washed for ultimate drape.',
    shortDescription: 'Vintage wash tee with subtle chest graphic.',
    brand: 'AURA Editorial',
    category: 'T-Shirts',
    gender: 'men',
    collectionName: 'Editorial Line',
    price: 2199,
    compareAtPrice: 2799,
    discountPercentage: 21,
    images: [
      'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=1000&q=80',
      'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=1000&q=80'
    ],
    colors: ['Charcoal Wash', 'Faded Olive'],
    sizes: ['S', 'M', 'L', 'XL'],
    stock: 20,
    sku: 'TEE-GRA-002',
    material: '100% Cotton',
    careInstructions: 'Machine wash cold. Do not iron print.',
    tags: ['tshirt', 'graphic', 'vintage'],
    rating: 4.6,
    reviewCount: 18,
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: false,
    isActive: true,
    createdAt: new Date()
  },
  {
    _id: 'prod_3',
    name: 'Relaxed Poplin Overshirt',
    slug: 'relaxed-poplin-overshirt',
    description: 'Cut from crisp Italian cotton poplin, this overshirt features a refined point collar, clean chest patch pocket, and mother-of-pearl buttons.',
    shortDescription: 'Crisp Italian poplin cotton overshirt for year-round layering.',
    brand: 'AURA Atelier',
    category: 'Shirts',
    gender: 'unisex',
    collectionName: 'Summer 2026',
    price: 3499,
    compareAtPrice: 4299,
    discountPercentage: 18,
    images: [
      'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=1000&q=80',
      'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=1000&q=80'
    ],
    colors: ['Sky Blue', 'White', 'Midnight Navy'],
    sizes: ['S', 'M', 'L', 'XL'],
    stock: 30,
    sku: 'SHRT-POP-001',
    material: '100% Fine Cotton Poplin',
    careInstructions: 'Dry clean recommended or machine wash cold gentle.',
    tags: ['shirt', 'poplin', 'overshirt'],
    rating: 4.9,
    reviewCount: 42,
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: true,
    isActive: true,
    createdAt: new Date()
  },
  {
    _id: 'prod_4',
    name: 'Architectural Heavy Hoodie',
    slug: 'architectural-heavy-hoodie',
    description: 'Engineered with 480 GSM organic French terry fleece. Features a double-layered hood without drawstrings, seamless kangaroo pocket, and structured ribbing.',
    shortDescription: '480 GSM French terry fleece hoodie with architectural silhouette.',
    brand: 'AURA Studio',
    category: 'Hoodies',
    gender: 'unisex',
    collectionName: 'Minimal Essentials',
    price: 4999,
    compareAtPrice: 5999,
    discountPercentage: 16,
    images: [
      'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=1000&q=80',
      'https://images.unsplash.com/photo-1509967419530-da38b4704bc6?w=1000&q=80'
    ],
    colors: ['Black', 'Concrete Gray', 'Bone'],
    sizes: ['S', 'M', 'L', 'XL'],
    stock: 50,
    sku: 'HD-HVY-001',
    material: '100% Organic French Terry Cotton',
    careInstructions: 'Machine wash cold gentle.',
    tags: ['hoodie', 'fleece', 'heavyweight'],
    rating: 4.95,
    reviewCount: 58,
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: true,
    isActive: true,
    createdAt: new Date()
  },
  {
    _id: 'prod_5',
    name: 'Minimal Wool Blend Tailored Blazer',
    slug: 'minimal-wool-blend-tailored-blazer',
    description: 'Single-breasted relaxed blazer tailored from virgin wool blend fabric. Fully lined with notch lapels and discreet side welt pockets.',
    shortDescription: 'Relaxed virgin wool blend single-breasted blazer.',
    brand: 'AURA Atelier',
    category: 'Jackets',
    gender: 'women',
    collectionName: 'Editorial Line',
    price: 8999,
    compareAtPrice: 10999,
    discountPercentage: 18,
    images: [
      'https://images.unsplash.com/photo-1548883354-7622d03aca27?w=1000&q=80',
      'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=1000&q=80'
    ],
    colors: ['Obsidian Black', 'Espresso Brown'],
    sizes: ['XS', 'S', 'M', 'L'],
    stock: 12,
    sku: 'JCK-BLZ-001',
    material: '70% Virgin Wool, 30% Polyester',
    careInstructions: 'Dry clean only.',
    tags: ['blazer', 'wool', 'tailored'],
    rating: 4.85,
    reviewCount: 19,
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: false,
    isActive: true,
    createdAt: new Date()
  },
  {
    _id: 'prod_6',
    name: 'Straight-Leg Raw Selvedge Jeans',
    slug: 'straight-leg-raw-selvedge-jeans',
    description: 'Classic high-rise straight leg jeans crafted from 13.5oz Japanese denim. Features five-pocket styling and custom leather patch detail.',
    shortDescription: '13.5oz raw Japanese selvedge denim straight jeans.',
    brand: 'AURA Denim',
    category: 'Jeans',
    gender: 'men',
    collectionName: 'Minimal Essentials',
    price: 4499,
    compareAtPrice: 5299,
    discountPercentage: 15,
    images: [
      'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=1000&q=80',
      'https://images.unsplash.com/photo-1582552938357-32b906df40cb?w=1000&q=80'
    ],
    colors: ['Raw Indigo', 'Stone Wash'],
    sizes: ['30', '32', '34', '36'],
    stock: 28,
    sku: 'JNS-STR-001',
    material: '100% Selvedge Cotton Denim',
    careInstructions: 'Wash rarely inside out.',
    tags: ['jeans', 'denim', 'selvedge'],
    rating: 4.9,
    reviewCount: 44,
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: true,
    isActive: true,
    createdAt: new Date()
  },
  {
    _id: 'prod_7',
    name: 'Architectural Silk Slip Dress',
    slug: 'architectural-silk-slip-dress',
    description: 'Bias-cut 100% mulberry silk slip dress featuring delicate adjustable shoulder straps and an asymmetrical midi hemline.',
    shortDescription: '100% Mulberry silk bias-cut slip dress.',
    brand: 'AURA Atelier',
    category: 'Dresses',
    gender: 'women',
    collectionName: 'Editorial Line',
    price: 7999,
    compareAtPrice: 9999,
    discountPercentage: 20,
    images: [
      'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=1000&q=80',
      'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=1000&q=80'
    ],
    colors: ['Emerald Green', 'Champagne', 'Onyx Black'],
    sizes: ['XS', 'S', 'M'],
    stock: 10,
    sku: 'DRS-SLK-001',
    material: '100% Mulberry Silk',
    careInstructions: 'Dry clean only.',
    tags: ['dress', 'silk', 'evening'],
    rating: 4.95,
    reviewCount: 37,
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: true,
    isActive: true,
    createdAt: new Date()
  },
  {
    _id: 'prod_8',
    name: 'Minimal Calfskin Leather Tote',
    slug: 'minimal-calfskin-leather-tote',
    description: 'Unstructured open tote handcrafted from full-grain Italian calfskin leather. Includes an unlined suede interior with detachable zip pouch.',
    shortDescription: 'Full-grain Italian calfskin leather unlined tote.',
    brand: 'AURA Goods',
    category: 'Accessories',
    gender: 'unisex',
    collectionName: 'Minimal Essentials',
    price: 6999,
    compareAtPrice: 8499,
    discountPercentage: 17,
    images: [
      'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=1000&q=80',
      'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=1000&q=80'
    ],
    colors: ['Black Leather', 'Cognac Tan'],
    sizes: ['One Size'],
    stock: 14,
    sku: 'ACC-TOT-001',
    material: '100% Full-Grain Italian Calfskin',
    careInstructions: 'Wipe clean with leather conditioner.',
    tags: ['leather', 'tote', 'bag'],
    rating: 4.9,
    reviewCount: 49,
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: true,
    isActive: true,
    createdAt: new Date()
  }
];

let mockOrders = [];
let mockCarts = {};
let mockWishlists = {};

let mockReviews = [
  {
    _id: 'rev_1',
    product: 'prod_1',
    productName: 'Heavyweight Boxy Tee',
    productImage: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=1000&q=80',
    user: 'user_cust_99',
    name: 'Sophia Laurent',
    email: 'customer@maisonvogue.fashion',
    rating: 5,
    title: 'Flawless drape and heavyweight 280 GSM feel',
    comment: 'The collar structure is exceptionally rigid and stays crisp after wash. Boxy silhouette without looking clumsy. Definitely ordering the Off-White variant next.',
    verifiedPurchase: true,
    status: 'approved',
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    adminReply: {
      comment: 'Thank you for your refined review, Sophia. We meticulously tailored the 280 GSM combed cotton collar to preserve its architectural silhouette over time.',
      repliedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
      repliedBy: 'Maison Vogue Concierge'
    }
  },
  {
    _id: 'rev_2',
    product: 'prod_1',
    productName: 'Heavyweight Boxy Tee',
    productImage: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=1000&q=80',
    user: 'user_cust_102',
    name: 'Julian Vance',
    email: 'julian@vance.design',
    rating: 5,
    title: 'Minimalist luxury at its finest',
    comment: 'Subtle dropped shoulders and dense fabric weave. Fits true to size with an elevated relaxed drape.',
    verifiedPurchase: true,
    status: 'approved',
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000),
    adminReply: {
      comment: 'Delighted to hear, Julian. Our Parisian atelier prioritizes timeless geometric drape over fleeting trends.',
      repliedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
      repliedBy: 'Maison Vogue Concierge'
    }
  },
  {
    _id: 'rev_3',
    product: 'prod_2',
    productName: 'Oversized Washed Graphic Tee',
    productImage: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=1000&q=80',
    user: 'user_cust_103',
    name: 'Claire Beauchamp',
    email: 'claire@fashionista.fr',
    rating: 4,
    title: 'Great vintage wash and texture',
    comment: 'The enzyme wash gives it an authentic worn-in drape right out of the packaging. The typography graphic is subtle and tasteful.',
    verifiedPurchase: true,
    status: 'approved',
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    adminReply: {
      comment: '',
      repliedAt: null,
      repliedBy: ''
    }
  }
];

const mockCoupons = [
  { _id: 'coup_1', code: 'AURA10', type: 'percentage', value: 10, minOrderValue: 1000, maxDiscount: 500, isActive: true },
  { _id: 'coup_2', code: 'WELCOME20', type: 'percentage', value: 20, minOrderValue: 2000, maxDiscount: 1000, isActive: true },
  { _id: 'coup_3', code: 'SUMMER500', type: 'fixed', value: 500, minOrderValue: 3000, maxDiscount: 0, isActive: true }
];

module.exports = {
  categoriesData,
  productsData,
  mockOrders,
  mockCarts,
  mockWishlists,
  mockReviews,
  mockCoupons
};
